apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ic010t54j-python 
  janus-idp.io/tekton: ic010t54j-python
  backstage.io/kubernetes-id: ic010t54j-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ic010t54j-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml